### PR TITLE
Initial implementation

### PR DESCRIPTION
**Pull request by delvedor**
This is the initial implementation of an idea of @mcollina and me.
As the repo name suggests, this library will help us to smoke test the new releases of fastify before we release them, just like [node citgm](https://github.com/nodejs/citgm).

Every suggestion is well accepted :)

cc @fastify/fastify

### CODE REVIEW

**Comment by jsumners** [comment]
So the idea is that this repo would verify that Fastify is not breaking compatibility with existing plugins?

**Comment by delvedor** [comment]
@jsumners exactly.
Or at least know that we are going to do that :P

**Comment by jsumners** [comment]
Sounds like a good plan to me.

Related: yesterday I started investigating setting up a dedicated VPS for automatically running benchmarks. But I'm not sure which GitHub webhook to key on for such a thing.

**Comment by mcollina** [comment]
LGTM, I would recommend setting up a pipeline in circleci for this.

**Comment by StarpTech** [comment]
What do you think about to implement a non-fastify specific implementation? It's quite useful for any framework which has a plugin system or e.g based on avvro. I think the effort would be minimal.

**Comment by mcollina** [comment]
I think the best approach should be to generalize https://github.com/nodejs/citgm

**Comment by delvedor** [comment]
@StarpTech we thought about that, but as said by @mcollina the best thing to do is to generalize https://github.com/nodejs/citgm.
In the mean time we'll use this solution that works well for our plugins.

**Pull request merged**
